apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: microservice-documenters-ternium-002
  namespace: default
  labels:
    app: api-microservice-documenters
    version: 0.0.2
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app: kafka-microservice-project-002
  serviceName: "kafka-microservice-project-service-002"
  template:
    metadata:
      labels:
        app: kafka-microservice-project-002
    spec:
      containers:
        - name: kafka-microservice-project-002
          image: documenters-consumers-microservice:0.0.2
          ports:
          - containerPort: 2023
          env:
            - name: HOST_MASTER
              value: kafka-microservice-project-2
            - name: SPRING_PROFILE
              value: prod
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: cfgmicroservicedocumenters002
                  key: MONGODB_URI
            - name: KAFKA_URI
              valueFrom:
                configMapKeyRef:
                  name: cfgmicroservicedocumenters002
                  key: KAFKA_URI
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: cfgmicroservicedocumenters002
                  key: PORT